name: Update Snake Animation

on:
  schedule:
    - cron: "0 12 * * *"  # Ao meio-dia UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: .github/snake/
          
      - name: Push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update snake animation" || exit 0
          git push
